import = [
     "uniswap"
]

[[spam.fuzz]]
param = "amountIn"
min = "1"
max = "100000000000000000"

[[spam]]
to = "{uniRouterV2}"
from = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
signature = "swapExactTokensForTokens(uint256 amountIn, uint256 amountOutMin, address[] path, address to, uint256 deadline) external returns (uint256[] memory)"
args = [
     "1000000000000000000",
     "1000",
     '[{weth}, {testToken}]',
     "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
     "10000000000000"
]

[[spam.fuzz]]
param = "amountIn"
min = "100000"
max = "10000000000"